### ISSUE TITLE
!?

### ISSUE THREAD

**Issue by mikeqoo1** [106062/api-test#1]
why? 106061? WTF?!

https://github.com/106062/api-test/blob/38e56b90e7608e751d3966fd10cb53b7f42312ff/docker-compose.yml#L6

**Comment by 106062** [comment]
[look here](https://hub.docker.com/repository/docker/106061/apiserver)

**Comment by mikeqoo1** [comment]
@106062  算你牛逼 我改天把信箱換我現在的好了 不然是收不到信的....

帳號就保留八= = 我猜crcft的CI/CD應該也是八 哈哈

**Comment by 106062** [comment]
yes you are right, that two image already download for over 1.2k & 2.8k

**Comment by 106062** [comment]
can try what happen after remove those image

**Comment by mikeqoo1** [comment]
you can update  those image BUT DON'T REMOVE ^^

**Comment by 106062** [comment]
[have no idea](https://github.com/mikeqoo1/node-crcft/blob/master/.gitlab-ci.yml)
who update the image version?
``` yaml
image: "106061/myimage:latest"
```

**Comment by mikeqoo1** [comment]
!? i do't know... use <Line>
